### PR TITLE
feat(component): Add apps component katib

### PR DESCRIPTION
**Pull request by rohank07**
Signed-off-by: rohank07 rohank_17@hotmail.ca

### CODE REVIEW

**Comment by rohank07** [comment]
I can do a `task stack:aaw:preview` locally for katib (commenting out the other resources). When I run all resources I get a timeout error running message.

**Comment by sylus** [comment]
Prolly just need to add a timeout to the kustomize build but thanks for the P.R.!

**Comment by sylus** [comment]
Althought the built isn't passing perhaps something is wrong:

[stacks > aaw] Error: accumulating resources: accumulation err='accumulating resources from '../../apps/katib/base': '/home/runner/work/aaw-kubeflow-manifests/aaw-kubeflow-manifests/kustomize/apps/katib/base' must resolve to a file': recursed merging from path '/home/runner/work/aaw-kubeflow-manifests/aaw-kubeflow-manifests/kustomize/apps/katib/base': may not add resource with an already registered id: ~G_v1_Namespace|~X|kubeflow
task: Failed to run task "k3d:test": task: Failed to run task "stack:aaw:preview": exit status 1

**Comment by sylus** [comment]
FIgured this one out and its my bad we had a folder for kfserving but we haven't looked at that yet and also was calling katib so we will tackle this when hit the kserve issue.

**Pull request merged**
