### PR TITLE
feat(component): Add apps component jupyter-web-app

### PR DESCRIPTION
**Pull request by rohank07**
Signed-off-by: rohank07 rohank_17@hotmail.ca

### CODE REVIEW

**Comment by sylus** [comment]
@rohank07 doesn't the cluster role come from Kubeflow are we performing adjustments on it?

**Comment by rohank07** [comment]
It appears we're modifying the cluster roles. 
Manifest on the left is the upstream cluster role. Manifest on the right is the patched cluster role
image

**Comment by sylus** [comment]
@zachomedia in the example above should we own the cluster roles or just apply our deltas via a strategic merge?

**Comment by sylus** [comment]
Overall this looks great @rohank07 just checking one thing and then will merge it.

**Comment by sylus** [comment]
Hey @rohank07 I might be wrong but I dont see a difference in output when commenting out:

```sh
# using a valueFrom instead of value
patches:
- target:
    kind: Deployment
    name: jupyter-web-app-deployment
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/env/1/value
    - op: remove
      path: /spec/template/spec/containers/0/env/2/value
```

**Comment by sylus** [comment]
Hey @rohank07 i made a few tiny adjustments but the end manifest is still the same.

**Comment by rohank07** [comment]
Okay to merge! Yeah, no differences in the patch :sweat_smile:

**Pull request merged**
