### PR TITLE
feat(component): Add common component knative

### PR DESCRIPTION
**Pull request by rohank07**
Signed-off-by: rohank07 rohank_17@hotmail.ca

### CODE REVIEW

**Comment by rohank07** [comment]
@sylus [Upstream](https://github.com/kubeflow/manifests/tree/v1.3.1/common/knative) installs Knative serving (v0.17.4) and Knative ingress controller for Istio (v0.17.1)
Back in June 2021 David Spek helped setup some of the groundwork for KF v1.3 apps on Kubeflow. For Knative he used Knative serving (v0.22.0) and Knative ingress controller for Istio (v0.22.0). What are your thoughts on which version we point to? In David's version he also installs eventing-core and commented it is optional (this was not done in v1,2). This PR installs v0.22.0.

**Comment by sylus** [comment]
We should stay as close to what we have in Kubeflow v2 and along with all of our customizations, but obviously being on the v1.3 line. So this is going to need a bit of work.

**Comment by rohank07** [comment]
There aren't any customizations from what we have in [v2](https://github.com/StatCan/aaw-kubeflow-manifests/blob/master/kustomize/knative/kustomization.yaml). v2 pointed to https://github.com/kubeflow/manifests/blob/v1.2-branch/knative/installs/generic/kustomization.yaml

**Comment by sylus** [comment]
Okay perfect then in v3 id stick as close to what kubeflow says we should run just as a baseline.

Its alot easier if something goes wrong to look at the kubeflow issue queue if we following what they are doing.

But i'll take a closer look at this one tomorrow :)

**Comment by sylus** [comment]
Please note I also made note in the AAW stack that we use the Istio Operator which does alot of the gateway handling for us so I didn't need to bring in that component which is mentioned in kubeflow/manifest as `common/istio-1-9/cluster-local-gateway/base`

**Comment by sylus** [comment]
Please note I also made note in the AAW stack that we use the Istio Operator which does alot of the gateway handling for us so I didn't need to bring in that component which is mentioned in kubeflow/manifest as `common/istio-1-9/cluster-local-gateway/base`

**Comment by rohank07** [comment]
Not sure if there is a cleaner way to use one patch to target multiple (in this case) deployment files.

**Pull request merged**
